### ISSUE TITLE
demo_call-log.py Either code or username with password has to be provided

### ISSUE THREAD

**Issue by grokify** [grokify/ringcentral-examples-python#1]
User receives the following error:

```
Traceback (most recent call last):
  File "C:/Python34/Ringcentral.py", line 20, in <module>
    os.getenv('MyPassword'))
  File "C:\Python34\lib\site-packages\ringcentral\platform\platform.py", line 105, in login
    raise e
  File "C:\Python34\lib\site-packages\ringcentral\platform\platform.py", line 82, in login
    raise Exception('Either code or username with password has to be provided')
Exception: Either code or username with password has to be provided
```

after modifying code:

```
import os
from dotenv import load_dotenv
load_dotenv(dotenv_path=os.getenv('ENV_PATH'))

from ringcentral import SDK

sdk = SDK(
    os.getenv('MyClientId'),
    os.getenv('Mysecret Key'),
    os.getenv('https://platform.devtest.ringcentral.com'))

platform = sdk.platform()
platform.login(
    os.getenv('MyUsername'),
    os.getenv('MyExtention'),
    os.getenv('MyPassword'))
```

**Comment by grokify** [comment]
> Either code or username with password has to be provided

The reason you are seeing this error is because of how the code is accepting user credentials. You have two basic options here:

1. Use an external .env file to hold your credentials and reference the file using an environment variable
2. Hard code your credentials in to the code and removing the os.getenv function calls (which go to the environment)

**Approach 1: Using .env Files**

Using external .env files is one recommended approach for storing credentials because it keeps them out of your code which often lives in a source control system and can be seen by many people. To do this, create a text file in the same directory as the `demo_call-log.py` script. You can place this anywhere, but we'll start with the same directory. The file should have the following content:

```
RINGCENTRAL_CLIENT_ID=MyClientId
RINGCENTRAL_CLIENT_SECRET=Mysecret Key
RINGCENTRAL_SERVER_URL=https://platform.devtest.ringcentral.com
RINGCENTRAL_USERNAME=MyUsername
RINGCENTRAL_EXTENSION=MyExtention
RINGCENTRAL_PASSWORD=MyPassword
```

Then reference the file in the ENV_PATH environment variable when you start the code:

```
$ ENV_PATH=.env python3 demo_call-log.py
```

You can also set the environment variable like the following. Adjust the path as appropriate

[Windows](http://www.dowdandassociates.com/blog/content/howto-set-an-environment-variable-in-windows-command-line-and-registry/)

```
C:\> setx ENV_PATH "%USERPROFILE%\.credentials\.env"
```

Linux, Unix, OS X

```
$ export ENV_PATH=$HOME/.credentials/.env
```

**Approach 2 Hardcoding Credentials**

You can hard code your credentials as shown, but you need to remove the `os.getenv` call because that takes an environment variable name and returns it's value. Here you don't want to be calling the environment, so modify the Python code as shown below. You can also remove the dependencies that are no longer used like dotenv and os.

```python
sdk = SDK(
    'MyClientId',
    'Mysecret Key',
    'https://platform.devtest.ringcentral.com')

platform = sdk.platform()
platform.login(
    'MyUsername',
    'MyExtention',
    'MyPassword')
```
